lerobot-record \
    --robot.type=so101_follower \
    --robot.port=/dev/tty.usbmodem5AE60533511 \
    --robot.id=my_awesome_follower_arm \
    --robot.cameras="{ top: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 25}, front: {type: opencv, index_or_path: 1, width: 640, height: 480, fps: 25}}" \
    --teleop.type=so101_leader \
    --teleop.port=/dev/tty.usbmodem5AE60574511 \
    --teleop.id=my_awesome_leader_arm \
    --display_data=true \
    --dataset.repo_id="${HF_USER}"/record-test--claire-may16-1301 \
    --dataset.num_episodes=5 \
    --dataset.single_task="Grab the red ring may 16 by Claire" \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 
